db.url=jdbc:mysql://localhost:3306/estacionamiento_utp?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
db.user=root
db.password=

report.output-dir=reportes
report.file-name=reporte_estacionamiento.xlsx
parking.hourly-rate=3.00
